# fly.toml app configuration file generated for fedi-canvas-bot on 2023-09-14T12:00:38+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fedi-canvas-bot"
primary_region = "mad"

[build]

[http_service]
  internal_port = 3000
  force_https = false
  auto_stop_machines = true
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]
